platform :ios, '7.0'
def shared_dependencies
  pod "AFNetworking", "~> 3.1.0"
  pod "SDWebImage", "~> 3.8.2"
  pod 'YYKit', '~> 1.0.9'
  pod 'Masonry', '~> 1.0.2'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'SVProgressHUD', '~> 2.0.4'
  pod 'LKDBHelper', '~> 2.4'
  pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
  pod 'BaiduMapKit', '~> 3.1.0'
  pod 'RealReachability', '~> 1.1.8'
  pod 'FBAllocationTracker', '~> 0.1.5'
  pod 'FBMemoryProfiler', '~> 0.1.3'
  pod 'FBRetainCycleDetector'
end

workspace "easywayout.xcodeproj"

target "easywayout" do
    shared_dependencies
end

